Error log on: 11/10/24 : 00:35
User Query:set a timer for 20 minutes
The following error occurred: run loop already started

In File: C:\Users\alies\GithubProjects\Jarvis_3.0\J3.pyw Function: start on 42 Code: self.__startListen()  # Starting listening for key input caused an error!

In File: C:\Users\alies\GithubProjects\Jarvis_3.0\J3.pyw Function: __startListen on 25 Code: self.handleQuery(self.inpHandler.startListen())  # Starting voice input caused an error!

In File: C:\Users\alies\GithubProjects\Jarvis_3.0\inputHandling.py Function: startListen on 35 Code: query: str | None = self.__recognizeAudio(audio) caused an error!

In File: C:\Users\alies\GithubProjects\Jarvis_3.0\inputHandling.py Function: __recognizeAudio on 23 Code: self.speaker.speak("Sorry Sir, I did not get that!")  # In case of an unexpected exception caused an error!

In File: C:\Users\alies\GithubProjects\Jarvis_3.0\outputHandling.py Function: speak on 17 Code: pyttsx3.speak(audio) caused an error!

In File: C:\Users\alies\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\__init__.py Function: speak on 30 Code: engine.runAndWait() caused an error!

In File: C:\Users\alies\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\engine.py Function: runAndWait on 177 Code: raise RuntimeError('run loop already started') caused an error!



